### ISSUE TITLE
Is it possible to request only specific part of speech?

### ISSUE THREAD

**Issue by tbazko** [ansteh/datamuse#1]
Would be nice if it'd be possible to request specifically nouns, verbs, adjectives etc. Is that possible somehow in current version?

**Comment by ansteh** [comment]
The official API http://www.datamuse.com/api/ allows to search for related words with context. Below code snippet performs a request for popular nouns modified by the given adjective. There are a lot of such constraints. Go to [datamuse](http://www.datamuse.com/api/) for more details. I hope i could help you.
```js
datamuse.request('words?rel_jja=gradual')
.then((json) => {
  console.log(json);
  //do it!
});
```
